# Generated by Django 5.2.16 on 2026-07-22 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('admission_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('student_class', models.PositiveSmallIntegerField()),
                ('section', models.CharField(max_length=5)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Maths', 'Maths'), ('Science', 'Science'), ('Social Science', 'Social Science')], max_length=32)),
                ('marks_obtained', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='academics.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'subject'), name='unique_student_subject')],
            },
        ),
    ]
